### ISSUE TITLE
Angular 7 + BabylonJS 3.3 + TypeScript 3.1 Compilation Error

### ISSUE THREAD

**Issue by JohnnyDevNull** [JohnnyDevNull/ng-babylon#1]
http://www.html5gamedevs.com/topic/40731-angular-7-babylonjs-33-typescript-31-compilation-error/

![image](https://user-images.githubusercontent.com/5759334/47185691-6e764080-d32e-11e8-80a7-a7791bdbbfb3.png)

https://github.com/JohnnyDevNull/ng-babylon-template/tree/angular-7

**Comment by JohnnyDevNull** [comment]
compiles with babylonjs@4.0.0-alpha.4

**Comment by zeser78** [comment]
Hey, thanks for your contribution to the two libraries and Angular. One question. Which easier to use with Angular, ThreeJS or BabylonJS? Thanks

**Comment by JohnnyDevNull** [comment]
Well because of BabylonJS is written in TypeScript it makes it easier to use it in Angular. 

You can also consider this: https://discourse.threejs.org/t/angular-threejs/2739/9

It is possible to use ThreeJS with Angular, but the lack of ES6 Module Support in ThreeJS makes it harder to master. They plan to improve this, but not in the near future.

**Comment by zeser78** [comment]
Thanks for the response. I looked at the discussion, and I tried to install OrbitControls, and I got it to work, but with the loaders, I have an error that doesn't find the file. I'll try to do it on BabylonJS,
